import { PublicReferencePage } from "@/components/public-reference-page";
import { publicMetadata } from "@/presentation/public-seo";

export const metadata = publicMetadata({
  path: "/astrology",
  title: "Astrology Calculation Reference",
  description:
    "Learn how tropical zodiac positions, aspects, houses, provenance, and tradition-framed interpretations are kept distinct.",
});

export default function AstrologyReferencePage() {
  return (
    <PublicReferencePage
      eyebrow="Astrology reference"
      title="How this astrology model separates calculation from interpretation"
      summary="A practical guide to the geometry, version trace, and limits behind the site's tropical astrology features."
      currentLabel="Astrology"
      currentPath="/astrology"
      sections={[
        {
          title: "Zodiac positions are circular geometry",
          paragraphs: [
            "A tropical ecliptic longitude is normalized to the interval from 0 degrees inclusive to 360 degrees exclusive. Each 30-degree sector maps to one zodiac sign, beginning with Aries at 0 degrees.",
            "The sign label is therefore a deterministic classification of a supplied longitude. It is not generated by an interpretation model.",
          ],
        },
        {
          title: "Aspects use explicit angles and orbs",
          paragraphs: [
            "An aspect compares the smallest angular separation between two positions with a configured target angle. The allowed orb, motion classification, aspect policy ID, and policy version belong in the result trace.",
          ],
          points: [
            "Conjunction: 0 degrees",
            "Sextile: 60 degrees",
            "Square: 90 degrees",
            "Trine: 120 degrees",
            "Opposition: 180 degrees",
          ],
        },
        {
          title: "Provider facts remain traceable",
          paragraphs: [
            "Planetary positions come through an EphemerisProvider boundary. Results retain provider, data, time-scale, reference-frame, zodiac-reference, coordinate-origin, and calculation metadata so they can be reproduced and audited.",
            "Interpretive wording may explain a validated fact, but it cannot change a longitude, house, aspect, event time, or score.",
          ],
        },
      ]}
      related={[
        {
          label: "Moon phase geometry",
          href: "/moon-phase",
          description:
            "See how phase angle, illumination, and the eight phase sectors are derived.",
        },
        {
          label: "Life Path arithmetic",
          href: "/numerology/life-path",
          description:
            "Follow the declared Pythagorean date-reduction convention.",
        },
        {
          label: "Aries daily sky",
          href: "/horoscope/aries",
          description:
            "View one general sign-target reflection with its calculation trace.",
        },
      ]}
    />
  );
}
